# Generated by Django 2.2.7 on 2019-11-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('time_records', '0001_initial'),
        ('beverages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='time_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_records.TimeRecord'),
        ),
    ]
