# Generated by Django 2.2.7 on 2019-11-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('most_sensitive', '300'), ('sensitive', '500'), ('least_sensitive', '700')], default='most_sensitive', max_length=9)),
            ],
        ),
    ]
