# Generated by Django 2.2.7 on 2019-11-23 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_records', '0002_dailyrecord_creator'),
        ('time_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='daily_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='daily_records.DailyRecord'),
        ),
    ]
