# Generated by Django 2.2.7 on 2019-11-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beverage', '0001_initial'),
        ('time_records', '0002_auto_20191123_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='beverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beverage.Beverage'),
        ),
    ]
